spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: $2a$10$BU2V22ofnBJgcjfOtogOjOkWxUuSnkl3oV3BKGPfup0P3YQXuTlXq
    oauth2:
      authorizationserver:
        endpoint:
          oidc:
            logout-uri: /logout
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:~/testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui